### ISSUE TITLE
attached xml files not shown in html

### ISSUE THREAD

**Issue by georgooty** [GHPReporter/Ghpr.NUnit.Examples#1]
Hi,

I have been using this tool for generating html result from nunit test result xml file. I'm attaching few xml file to testcontext .Though, that xml attachment files are not shown in html report. 

I verified that the attached section exists in nunit test results xml file.

Can you help me to resolve this issue

Regards,
George

**Comment by elv1s42** [comment]
Hi @georgooty !
This is a new feature of NUnit which is not supported at the moment. 
Can you please provide some sample code of how you are using xml files in testcontext?

I will create a new issue in Ghpr.NUnit repository. This repository is for test examples.

Thank you.

**Comment by georgooty** [comment]
yes, its new feature in NUnit.

I used the below code snippet,

TestContext.AddTestAttachment(fileName,"description");

Ok. Thank you.

Regards,
George

**Comment by elv1s42** [comment]
@georgooty , I've created a new ussie in Core repository: https://github.com/GHPReporter/Ghpr.Core/issues/46

Closing this one.

Thank you!
